version: '3.8'

services:
  mysql:
    image: mysql:8.0.40
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    restart: always
    environment:
      MYSQL_DATABASE: millie
      MYSQL_ROOT_PASSWORD: local
      MYSQL_USER: local
      MYSQL_PASSWORD: local
    ports:
      - "3306:3306"