# Generated by Django 5.1.7 on 2025-03-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0002_alter_category_created_at_alter_category_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="coupons",
            field=models.ManyToManyField(blank=True, to="products.coupon"),
        ),
    ]
